# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: LIN
description: GO
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://linzerui.github.io" # the base hostname & protocol for your site
excerpt_separator: <!-- more -->

permalink: pretty

exclude: ["node_modules"]

# Build settings
markdown: kramdown
